# -*- coding: utf-8 -*-
"""exercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bOdVrj8oL3vERYMCcwn6eP3G-v-8tOn
"""

peso = eval(input('Digite seu peso: '))
altura = eval(input('Digite sua altura: '))
imc = peso/(altura**2)
print ('IMC = ', imc)